server:
  port: 8081
logging:
  level:
    root: INFO
mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  main:
    allow-bean-definition-overriding: true
  application:
    name: demo
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/testjava
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true